# Alcohol Dataset



Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.


### Step 1. Import the necessary libraries

In [3]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv")
df.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

In [5]:
df.shape

(193, 6)

In [6]:
df.describe()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
count,193.000000,193.000000,193.000000,193.000000
mean,106.160622,80.994819,49.450777,4.717098
std,101.143103,88.284312,79.697598,3.773298
min,0.000000,0.000000,0.000000,0.000000
25%,20.000000,4.000000,1.000000,1.300000
50%,76.000000,56.000000,8.000000,4.200000
75%,188.000000,128.000000,59.000000,7.200000
max,376.000000,438.000000,370.000000,14.400000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       193 non-null    str
 1   beer_servings                 193 non-null    int64
 2   spirit_servings               193 non-null    int64
 3   wine_servings                 193 non-null    int64
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     170 non-null    str
dtypes: float64(1), int64(3), str(2)
memory usage: 11.1 KB

### Step 3. Assign it to a variable called drinks.

In [54]:
drinks = df
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

### Step 4. Which continent drinks more beer on average?

In [55]:
drinks.groupby("continent")["beer_servings"].mean().sort_values(ascending=False)

continent
EU    193.777778
SA    175.083333
OC     89.687500
AF     61.471698
AS     37.045455
Name: beer_servings, dtype: float64

In [58]:
max_beer = drinks.groupby("continent")["beer_servings"].mean().sort_values(ascending=False)
print(max_beer.idxmax(),max_beer.max())

EU 193.77777777777777

### Step 5. For each continent print the statistics for wine consumption.

In [61]:
drinks.groupby("continent")["wine_servings"].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

In [62]:
drinks.groupby("continent")["wine_servings"].agg(["mean","median","std","max","min"])

                 mean  median        std  max  min
continent
AF          16.264151     2.0  38.846419  233    0
AS           9.068182     1.0  21.667034  123    0
EU         142.222222   128.0  97.421738  370    0
OC          35.625000     8.5  64.555790  212    0
SA          62.416667    12.0  88.620189  221    1

### Step 6. Print the mean alcohol consumption per continent for every column

In [64]:
df.groupby("continent")[["total_litres_of_pure_alcohol","beer_servings","spirit_servings","wine_servings","total_litres_of_pure_alcohol"]].mean()

,total_litres_of_pure_alcohol,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,,
AF,3.007547,61.471698,16.339623,16.264151,3.007547
AS,2.170455,37.045455,60.840909,9.068182,2.170455
EU,8.617778,193.777778,132.555556,142.222222,8.617778
OC,3.381250,89.687500,58.437500,35.625000,3.381250
SA,6.308333,175.083333,114.750000,62.416667,6.308333

In [63]:
drinks.groupby("continent").mean(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

### Step 7. Print the median alcohol consumption per continent for every column

In [65]:
drinks.groupby("continent").median(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 8. Find out (list) the names of countries which shows no cosumption of any kind of drink

In [21]:
df.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

In [71]:
zero_consumption = drinks[
    (drinks["beer_servings"] == 0) &
    (drinks["spirit_servings"] == 0) &
    (drinks["wine_servings"] == 0) &
    (drinks["total_litres_of_pure_alcohol"] == 0)
]

print(zero_consumption["country"].to_list())

['Afghanistan', 'Bangladesh', 'North Korea', 'Iran', 'Kuwait', 'Libya', 'Maldives', 'Marshall Islands', 'Mauritania', 'Monaco', 'Pakistan', 'San Marino', 'Somalia']

### Step 9. Find out (list) the names of countries which has more wine_servings than beer_servings from Europe

In [72]:
sum(df["continent"].str.lower() == "eu")

45

In [73]:
df[(df["wine_servings"] > df["beer_servings"]) & (df["continent"] == "EU")]["country"]

3          Andorra
42         Croatia
48         Denmark
61          France
64         Georgia
67          Greece
83           Italy
99      Luxembourg
113     Montenegro
136       Portugal
156       Slovenia
165         Sweden
166    Switzerland
Name: country, dtype: str

In [74]:
df[(df["wine_servings"] > df["beer_servings"]) & (df["continent"] == "EU")]["country"].to_list()

['Andorra',
 'Croatia',
 'Denmark',
 'France',
 'Georgia',
 'Greece',
 'Italy',
 'Luxembourg',
 'Montenegro',
 'Portugal',
 'Slovenia',
 'Sweden',
 'Switzerland']

### Step 10. Find out (list) the names of countries from Asia which has more beer consumption than avg beer_consumption of Europe

In [46]:
df.groupby("continent")["beer_servings"].mean()

continent
AF     61.471698
AS     37.045455
EU    193.777778
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64

In [50]:
s7 = df.groupby("continent")["beer_servings"].mean().iloc[2]

In [53]:
df[(df["continent"] == "AS") & (df["beer_servings"] > s7)]["country"].to_list()

['Russian Federation']