In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("student_performance_dataset - student_performance_dataset.csv")
df

,student_id,age,gender,study_hours_per_day,attendance_percentage,previous_exam_score,assignments_completed_percentage,sleep_hours,social_media_hours,practice_tests_completed,final_exam_score
0,1001,17,Male,3.7,77.5,80.7,79.5,7.2,4.4,5,78.9
1,1002,23,Male,5.5,93.5,44.0,65.7,8.4,2.6,7,73.4
2,1003,22,Female,0.5,82.9,55.1,79.4,5.1,0.3,7,78.0
3,1004,20,Female,1.6,87.4,93.8,65.3,7.2,0.1,7,62.8
4,1005,20,Female,2.4,67.2,81.9,60.4,6.4,2.8,5,55.4
...,...,...,...,...,...,...,...,...,...,...,...
495,1496,20,Male,1.7,79.5,65.2,79.1,7.5,1.4,8,75.3
496,1497,17,Female,1.1,71.0,65.2,79.8,5.6,3.5,8,62.4
497,1498,19,Female,0.5,71.7,63.5,80.6,8.3,3.1,6,52.7
498,1499,24,Male,2.0,85.3,55.3,94.6,9.5,3.1,9,68.6
499,1500,20,Male,5.8,61.9,42.7,60.6,8.1,2.9,4,60.9

In [5]:
df.isna().sum()

student_id                          0
age                                 0
gender                              0
study_hours_per_day                 0
attendance_percentage               0
previous_exam_score                 0
assignments_completed_percentage    0
sleep_hours                         0
social_media_hours                  0
practice_tests_completed            0
final_exam_score                    0
dtype: int64

In [7]:
df.describe()

,student_id,age,study_hours_per_day,attendance_percentage,previous_exam_score,assignments_completed_percentage,sleep_hours,social_media_hours,practice_tests_completed,final_exam_score
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,1250.500000,20.494000,3.794200,77.141800,63.715800,77.851400,7.067600,2.525200,4.938000,64.383800
std,144.481833,2.276033,1.476328,12.124987,14.302965,15.547386,1.090141,1.249451,2.468673,10.344073
min,1001.000000,17.000000,0.500000,42.500000,20.000000,29.000000,4.000000,0.000000,0.000000,28.000000
25%,1125.750000,19.000000,2.800000,69.550000,53.650000,67.650000,6.300000,1.700000,3.000000,57.000000
50%,1250.500000,20.000000,3.800000,77.700000,64.850000,78.700000,7.000000,2.550000,5.000000,64.350000
75%,1375.250000,22.250000,4.700000,85.325000,73.550000,90.300000,7.800000,3.300000,6.000000,71.250000
max,1500.000000,24.000000,8.000000,100.000000,98.000000,100.000000,10.000000,6.500000,14.000000,95.500000